### ISSUE TITLE
Provide an easy way to duplicate model like `createOrUpdate`

### ISSUE THREAD

**Issue by itmammoth** [itmammoth/Tamotsu#10]
From #7

**Comment by actongorton** [comment]
This would be a super nice feature!

I'm not sure if I'm doing this correctly, but I've been using an if/else pattern to test if the id is found in another sheet, like so:

```
var db_record = RecordsDatabase.find(cc_record['#']);
  
  if (!db_record){
    db_record = new RecordsDatabase({
      'update': 'TRUE',
      '#': cc_record['#'],
      'uid': uid
    });
  }
  else {
    db_record['update'] = true;
    db_record['uid'] = uid;
  }

  // save the record
  db_record.save();
```

**Comment by itmammoth** [comment]
A couple of things you should know are,

1. Id must be a unique value in a spreadsheet.
1. Currently, auto-increment id is only supported. (see the #7)
1. `Table.find` throws "Record not found" exception if there is no record with the given id.
So, you need to use `try ~ catch` statement like below

```
var db_record;
try {
  db_record = RecordsDatabase.find(cc_record['#']);
  // Found
  ...
} catch (e) {
  // Not found
  ...
}
db_record.save();
```

**Comment by actongorton** [comment]
I branched the repo and modified the `find` method to return `false` instead of the `record not found` warning.

**Comment by ralphilius** [comment]
@actongorton You can use below approach:

    function getRecordById(id){
        try {
            RecordsDatabase.find(id);
            return true;
        } catch(e){
            return false;
        }
    }

**Comment by itmammoth** [comment]
Finally, I made an implementation for this issue.
Try with version `30`.

```
var agent = new Agent({
  '#': '999',
  'First Name': 'Morgan',
  'Last Name': 'Grimes',
  'Gender': 'Male',
  'Salary': 50,
});
Agent.createOrUpdate(agent);

// or with attributes
Agent.createOrUpdate({
  '#': '999',
  'First Name': 'Morgan',
  'Last Name': 'Grimes',
  'Gender': 'Male',
  'Salary': 50,
});
```
