### ISSUE TITLE
expose tamotsu as REST endpoints

### ISSUE THREAD

**Issue by coderofsalvation** [itmammoth/Tamotsu#15]
Hi,

First of all thanks for making/maintaining tamotsu.
I've started this middleware for [Gexpress](https://github.com/coderofsalvation/Gexpress) which allows you to execute tamotsu using webrequests (in 4 lines):

[Gexpress-middleware-RESTsheet](https://github.com/coderofsalvation/Gexpress-middleware-RESTsheet)

Hope it will be useful to anyone.

> this issue can be closed

**Comment by itmammoth** [comment]
Great work, @coderofsalvation 
It seems challenging, but I think it would be useful to develop a simple RESTful application.
Glad to be of any help.
Thanks.
