### ISSUE TITLE
Table.update() override unspecified value

### ISSUE THREAD

**Issue by ralphilius** [itmammoth/Tamotsu#17]
Let's say I have a row with below information: 

```
{
  "id": 1,
  "someattr": "somevalue",
  "anotherattr": "anothervalue"
}
```
I want to createOrUpdate this object with below script
```javascript
var newObject = {
  someattr: "someothervalue"
}

SomeTable.createOrUpdate(newObject);
```

The old object turn out like this:
```
{
  "id": 1,
  "someattr": "somevalue",
  "anotherattr": ""
}
```

Should we change this to `updateAttributes` instead? https://github.com/itmammoth/Tamotsu/blob/master/src/models/Table.js#L177

**Comment by itmammoth** [comment]
```
var newObject = {
  id: 1,
  someattr: "someothervalue"
}
```
