### ISSUE TITLE
How .save() update wehere multi column .all() result?

### ISSUE THREAD

**Issue by khakimsetia** [itmammoth/Tamotsu#20]
var list = Agent.where({ Gender: 'Male' }).all(); 
// Log : [{First Name : "Jhon", Salary = 100},{First Name : "Charles", Salary = 200}]

how update / save multi result?
i want update Salary = 0 Where Gender = Male.

**Comment by itmammoth** [comment]
How about iterating through the list and updating the model one by one?
Unfortunately, multiple updating is not supported  at the moment.

**Comment by khakimsetia** [comment]
Oke,,
i try it... But what method .save() for .all() result?

```
var list = Agent.where({ Gender: 'Male' }).all();
for(let i = 0; i<Object.keys(list).length; i++){
    Logger.log(list[i].salary); //log salary result successed.    

    //save. this wrong.
    list[i]['salary'] = 0;
    list[i].save();
  }
```

Can you help me?
how method save working?

**Comment by itmammoth** [comment]
It seems to work correctly to me.
My code is below.

```javascript
function myFunction() {
  Tamotsu.initialize();
  const Agent = Tamotsu.Table.define({ sheetName: 'Agents' }, {});
  
  const agents = Agent.where({ Gender: 'Male' }).all();
  for (const agent of agents) {
    agent['Salary'] = 0;
    agent.save();
  }
}
```

**Comment by khakimsetia** [comment]
Oh i see,,......
i had trouble because My table is Not contain Coloum '#'.

Thank you very much.
your libray is very useful for me.
