### ISSUE TITLE
Can i use NOT conditional in Where function?

### ISSUE THREAD

**Issue by khakimsetia** [itmammoth/Tamotsu#21]
How about NOT function in WHERE?
like "Select all Agent Where Salary is NOT 100;"
thankyou.

**Comment by itmammoth** [comment]
https://github.com/itmammoth/Tamotsu#tamotsutablewhereconditions

Just give `where` a predicate function.

**Comment by itmammoth** [comment]
```javascript
Agent.where(function(agent) { return agent['Salary'] !== 150; })
```

**Comment by khakimsetia** [comment]
Ok it's clearly...
Thankyou
