### ISSUE TITLE
Tamotsu can't get correct area when has empty column header name Intermediate between column

### ISSUE THREAD

**Issue by ggafiled** [itmammoth/Tamotsu#22]
**First**, I must thank you so much. that you develop this library to manage and query in google sheet. but I found the issue follow to the questions. can you recommend a way to fix this issue? 
* In my opinion. I wanna add one parameter to the library like sheetName when creating a new instance the parameter that I wanna add is sheetRange (optional) to tell tamotsu know bounding to query. 

Thank you again.
 _**Sorry, my English skill isn't fluent.**_

**Comment by itmammoth** [comment]
Since the column name is the only way to access the value it points to, an unnamed column cannot be acceptable. 
Or do you mean that the data is also empty as well as its header?
