### ISSUE TITLE
Problem on save update data.

### ISSUE THREAD

**Issue by czalaira** [itmammoth/Tamotsu#6]
When I updates some cells name with " class" on sheet data doesn't contain the text. But it contains this function.

value of my updated cell class become like this

function () {
    return Parent.apply(this, arguments);
}

How can I use "class" as property name?

**Comment by itmammoth** [comment]
Hi, @czalaira 
"class" was reserved by the careless implementation, so I fixed it just now.
Try with the latest version.
Thanks!

**Comment by czalaira** [comment]
Thank you so much!!!. @itmammoth.
